spring:
  cloud:
    gateway:
      routes:
        - id: main-backend
          uri: lb://main-backend
          predicates:
            - Path=/users/**,/user/**,/notifications/**,/v3/schedules/**,/v3/schedule/**,/schedule/**
          filters:
            - TelegramBotAuthFilter
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/v2/notifications/**
          filters:
            - TelegramBotAuthFilter
            - StripPrefix=1
        - id: remote-schedule-service
          uri: lb://remote-schedule-service
          predicates:
            - Path=/remote-schedule,/remote-schedule/**
        - id: remote-schedule-service-management
          uri: lb://remote-schedule-service
          filters:
            - TelegramBotAuthFilter
          predicates:
            - Path=/remote-schedule-management
