spring:
  cloud:
    gateway:
      routes:
        - id: main-backend
          uri: lb://main-backend
          predicates:
            - Path=/users/**,/user/**,/notifications/**,/v3/schedules/**,/v3/schedule/**,/schedule/**
          filters:
            - TelegramBotAuthFilter
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/v2/notifications/**
          filters:
            - TelegramBotAuthFilter
            - StripPrefix=1